### ISSUE TITLE
PA Review: User Pages

### ISSUE THREAD

**Issue by chrisbigelow** [chrisbigelow/soundstand#1]

**Comment by LochandQuay** [comment]
@chrisbigelow 

Functionality Issues: 
- [x] User page is not displaying only the songs uploaded by that user. 
- [x] There's a broken image on the user page--potentially for a user profile image but there's no place to add a user profile image. Should at least have a default image for now. 
    - [x] Wait I just found it. It really doesn't stand out. I'd make it smaller and white.
- [x] Update user info form is out of whack. The location label is below the input field. 
- [x] After updating user info, should redirect to user page, not index.

**Comment by chrisbigelow** [comment]
fixed functionality issues
