### ISSUE TITLE
PA Review: Song CRUD

### ISSUE THREAD

**Issue by chrisbigelow** [chrisbigelow/soundstand#4]

**Comment by LochandQuay** [comment]
@chrisbigelow 

Functionality Issues:
- [x] Why am I seeing other users' songs on my user page? 
- [x] Song Upload Form needs form errors
- [x] After clicking submit, would prefer to see some kind of loading button or something.
- [x] I clicked on the song I just uploaded and it took me the song's page but it displayed information for a different song. 
- [x] Edit form should populate the fields with the current information. I wasn't sure if not filling out those fields would've resulted in those fields not changing or becoming empty.

Styling Issues:
- [x] Need to make sure your images don't get squished or stretched. I would recommend an `object-fit: cover` or something.
- [x] Song Upload Form: Need padding on the input, and probably smaller font on it. It's really big.

**Comment by chrisbigelow** [comment]
fixed functionality issues

**Comment by LochandQuay** [comment]
Console Errors:
- [x] (around form) Warning: Invalid DOM property `class`. Did you mean `className`?

Functionality Issues: 
- [x] Errors didn't show, it just sent me to the loading image (which is super cool, btw)
- [x] Valid inputs didn't go through, either.

Styling Issues: 
- [x] If you're on a smaller screen + have DevTools open, your album/profile images get squished to the side of the page (on show pages). Probably still missing some kind of padding...maybe on the main div?
